// Emoji data with categories and aliases for search
export interface Emoji {
  emoji: string;
  name: string;
  aliases: string[];
  category: string;
}

export interface EmojiCategory {
  name: string;
  icon: string;
  emojis: Emoji[];
}

// Common emojis organized by category
export const emojiCategories: EmojiCategory[] = [
  {
    name: "Smileys",
    icon: "😊",
    emojis: [
      { emoji: "😀", name: "grinning", aliases: ["grinning", "happy", "smile"], category: "Smileys" },
      { emoji: "😃", name: "smiley", aliases: ["smiley", "happy", "joy"], category: "Smileys" },
      { emoji: "😄", name: "smile", aliases: ["smile", "happy", "joy", "laugh"], category: "Smileys" },
      { emoji: "😁", name: "grin", aliases: ["grin", "happy", "smile"], category: "Smileys" },
      { emoji: "😆", name: "laughing", aliases: ["laughing", "satisfied", "happy"], category: "Smileys" },
      { emoji: "😅", name: "sweat_smile", aliases: ["sweat_smile", "nervous", "relief"], category: "Smileys" },
      { emoji: "🤣", name: "rofl", aliases: ["rofl", "lol", "laughing", "rolling"], category: "Smileys" },
      { emoji: "😂", name: "joy", aliases: ["joy", "tears", "laugh", "happy", "lol"], category: "Smileys" },
      { emoji: "🙂", name: "slightly_smiling_face", aliases: ["slightly_smiling_face", "smile"], category: "Smileys" },
      { emoji: "🙃", name: "upside_down_face", aliases: ["upside_down_face", "silly"], category: "Smileys" },
      { emoji: "😉", name: "wink", aliases: ["wink", "flirt"], category: "Smileys" },
      { emoji: "😊", name: "blush", aliases: ["blush", "happy", "shy", "smile"], category: "Smileys" },
      { emoji: "😇", name: "innocent", aliases: ["innocent", "angel", "halo"], category: "Smileys" },
      { emoji: "🥰", name: "smiling_face_with_hearts", aliases: ["love", "hearts", "adore"], category: "Smileys" },
      { emoji: "😍", name: "heart_eyes", aliases: ["heart_eyes", "love", "crush", "adore"], category: "Smileys" },
      { emoji: "🤩", name: "star_struck", aliases: ["star_struck", "excited", "wow"], category: "Smileys" },
      { emoji: "😘", name: "kissing_heart", aliases: ["kissing_heart", "kiss", "love"], category: "Smileys" },
      { emoji: "😗", name: "kissing", aliases: ["kissing", "kiss"], category: "Smileys" },
      { emoji: "😚", name: "kissing_closed_eyes", aliases: ["kissing_closed_eyes", "kiss"], category: "Smileys" },
      { emoji: "😙", name: "kissing_smiling_eyes", aliases: ["kissing_smiling_eyes", "kiss"], category: "Smileys" },
      { emoji: "🥲", name: "smiling_face_with_tear", aliases: ["happy_tear", "grateful"], category: "Smileys" },
      { emoji: "😋", name: "yum", aliases: ["yum", "delicious", "tasty", "tongue"], category: "Smileys" },
      { emoji: "😛", name: "stuck_out_tongue", aliases: ["stuck_out_tongue", "tongue", "playful"], category: "Smileys" },
      { emoji: "😜", name: "stuck_out_tongue_winking_eye", aliases: ["wink_tongue", "crazy", "playful"], category: "Smileys" },
      { emoji: "🤪", name: "zany_face", aliases: ["zany_face", "crazy", "wild"], category: "Smileys" },
      { emoji: "😝", name: "stuck_out_tongue_closed_eyes", aliases: ["tongue", "playful"], category: "Smileys" },
      { emoji: "🤑", name: "money_mouth_face", aliases: ["money_mouth_face", "money", "rich"], category: "Smileys" },
      { emoji: "🤗", name: "hugs", aliases: ["hugs", "hug", "embrace"], category: "Smileys" },
      { emoji: "🤭", name: "hand_over_mouth", aliases: ["hand_over_mouth", "oops", "shy"], category: "Smileys" },
      { emoji: "🤫", name: "shushing_face", aliases: ["shushing_face", "quiet", "secret"], category: "Smileys" },
      { emoji: "🤔", name: "thinking", aliases: ["thinking", "hmm", "consider"], category: "Smileys" },
      { emoji: "🤐", name: "zipper_mouth_face", aliases: ["zipper_mouth_face", "secret", "quiet"], category: "Smileys" },
      { emoji: "🤨", name: "raised_eyebrow", aliases: ["raised_eyebrow", "skeptical", "suspicious"], category: "Smileys" },
      { emoji: "😐", name: "neutral_face", aliases: ["neutral_face", "meh", "indifferent"], category: "Smileys" },
      { emoji: "😑", name: "expressionless", aliases: ["expressionless", "blank"], category: "Smileys" },
      { emoji: "😶", name: "no_mouth", aliases: ["no_mouth", "silent", "speechless"], category: "Smileys" },
      { emoji: "😏", name: "smirk", aliases: ["smirk", "smug"], category: "Smileys" },
      { emoji: "😒", name: "unamused", aliases: ["unamused", "bored", "annoyed"], category: "Smileys" },
      { emoji: "🙄", name: "roll_eyes", aliases: ["roll_eyes", "eye_roll", "whatever"], category: "Smileys" },
      { emoji: "😬", name: "grimacing", aliases: ["grimacing", "awkward", "nervous"], category: "Smileys" },
      { emoji: "😮‍💨", name: "exhale", aliases: ["exhale", "sigh", "relief"], category: "Smileys" },
      { emoji: "🤥", name: "lying_face", aliases: ["lying_face", "lie", "pinocchio"], category: "Smileys" },
      { emoji: "😌", name: "relieved", aliases: ["relieved", "relaxed", "calm"], category: "Smileys" },
      { emoji: "😔", name: "pensive", aliases: ["pensive", "sad", "thoughtful"], category: "Smileys" },
      { emoji: "😪", name: "sleepy", aliases: ["sleepy", "tired"], category: "Smileys" },
      { emoji: "🤤", name: "drooling_face", aliases: ["drooling_face", "drool", "yummy"], category: "Smileys" },
      { emoji: "😴", name: "sleeping", aliases: ["sleeping", "zzz", "tired"], category: "Smileys" },
      { emoji: "😷", name: "mask", aliases: ["mask", "sick", "ill"], category: "Smileys" },
      { emoji: "🤒", name: "face_with_thermometer", aliases: ["sick", "fever", "ill"], category: "Smileys" },
      { emoji: "🤕", name: "face_with_head_bandage", aliases: ["hurt", "injured", "bandage"], category: "Smileys" },
      { emoji: "🤢", name: "nauseated_face", aliases: ["nauseated_face", "sick", "gross"], category: "Smileys" },
      { emoji: "🤮", name: "vomiting_face", aliases: ["vomiting_face", "sick", "puke"], category: "Smileys" },
      { emoji: "🤧", name: "sneezing_face", aliases: ["sneezing_face", "achoo", "sick"], category: "Smileys" },
      { emoji: "🥵", name: "hot_face", aliases: ["hot_face", "hot", "sweating"], category: "Smileys" },
      { emoji: "🥶", name: "cold_face", aliases: ["cold_face", "cold", "freezing"], category: "Smileys" },
      { emoji: "🥴", name: "woozy_face", aliases: ["woozy_face", "drunk", "dizzy"], category: "Smileys" },
      { emoji: "😵", name: "dizzy_face", aliases: ["dizzy_face", "unconscious"], category: "Smileys" },
      { emoji: "🤯", name: "exploding_head", aliases: ["exploding_head", "mind_blown", "shocked"], category: "Smileys" },
      { emoji: "🤠", name: "cowboy_hat_face", aliases: ["cowboy_hat_face", "cowboy"], category: "Smileys" },
      { emoji: "🥳", name: "partying_face", aliases: ["partying_face", "party", "celebrate"], category: "Smileys" },
      { emoji: "🥸", name: "disguised_face", aliases: ["disguised_face", "disguise"], category: "Smileys" },
      { emoji: "😎", name: "sunglasses", aliases: ["sunglasses", "cool", "awesome"], category: "Smileys" },
      { emoji: "🤓", name: "nerd_face", aliases: ["nerd_face", "nerd", "geek"], category: "Smileys" },
      { emoji: "🧐", name: "monocle_face", aliases: ["monocle_face", "fancy", "inspect"], category: "Smileys" },
      { emoji: "😕", name: "confused", aliases: ["confused", "puzzled"], category: "Smileys" },
      { emoji: "😟", name: "worried", aliases: ["worried", "concerned"], category: "Smileys" },
      { emoji: "🙁", name: "slightly_frowning_face", aliases: ["frown", "sad"], category: "Smileys" },
      { emoji: "😮", name: "open_mouth", aliases: ["open_mouth", "surprised", "shocked"], category: "Smileys" },
      { emoji: "😯", name: "hushed", aliases: ["hushed", "surprised"], category: "Smileys" },
      { emoji: "😲", name: "astonished", aliases: ["astonished", "shocked", "surprised"], category: "Smileys" },
      { emoji: "😳", name: "flushed", aliases: ["flushed", "embarrassed", "shy"], category: "Smileys" },
      { emoji: "🥺", name: "pleading_face", aliases: ["pleading_face", "please", "puppy_eyes"], category: "Smileys" },
      { emoji: "😦", name: "frowning", aliases: ["frowning", "sad"], category: "Smileys" },
      { emoji: "😧", name: "anguished", aliases: ["anguished", "worried"], category: "Smileys" },
      { emoji: "😨", name: "fearful", aliases: ["fearful", "scared", "afraid"], category: "Smileys" },
      { emoji: "😰", name: "cold_sweat", aliases: ["cold_sweat", "nervous", "anxious"], category: "Smileys" },
      { emoji: "😥", name: "disappointed_relieved", aliases: ["disappointed_relieved", "phew"], category: "Smileys" },
      { emoji: "😢", name: "cry", aliases: ["cry", "sad", "tear"], category: "Smileys" },
      { emoji: "😭", name: "sob", aliases: ["sob", "crying", "sad", "tears"], category: "Smileys" },
      { emoji: "😱", name: "scream", aliases: ["scream", "scared", "shocked"], category: "Smileys" },
      { emoji: "😖", name: "confounded", aliases: ["confounded", "frustrated"], category: "Smileys" },
      { emoji: "😣", name: "persevere", aliases: ["persevere", "struggling"], category: "Smileys" },
      { emoji: "😞", name: "disappointed", aliases: ["disappointed", "sad"], category: "Smileys" },
      { emoji: "😓", name: "sweat", aliases: ["sweat", "tired", "worried"], category: "Smileys" },
      { emoji: "😩", name: "weary", aliases: ["weary", "tired", "upset"], category: "Smileys" },
      { emoji: "😫", name: "tired_face", aliases: ["tired_face", "exhausted"], category: "Smileys" },
      { emoji: "🥱", name: "yawning_face", aliases: ["yawning_face", "yawn", "tired"], category: "Smileys" },
      { emoji: "😤", name: "triumph", aliases: ["triumph", "angry", "frustrated"], category: "Smileys" },
      { emoji: "😡", name: "rage", aliases: ["rage", "angry", "mad"], category: "Smileys" },
      { emoji: "😠", name: "angry", aliases: ["angry", "mad", "annoyed"], category: "Smileys" },
      { emoji: "🤬", name: "cursing_face", aliases: ["cursing_face", "swearing", "angry"], category: "Smileys" },
      { emoji: "😈", name: "smiling_imp", aliases: ["smiling_imp", "devil", "evil"], category: "Smileys" },
      { emoji: "👿", name: "imp", aliases: ["imp", "devil", "angry"], category: "Smileys" },
      { emoji: "💀", name: "skull", aliases: ["skull", "dead", "death"], category: "Smileys" },
      { emoji: "☠️", name: "skull_and_crossbones", aliases: ["skull_and_crossbones", "danger", "death"], category: "Smileys" },
      { emoji: "💩", name: "poop", aliases: ["poop", "shit", "crap", "hankey"], category: "Smileys" },
      { emoji: "🤡", name: "clown_face", aliases: ["clown_face", "clown"], category: "Smileys" },
      { emoji: "👹", name: "ogre", aliases: ["ogre", "monster"], category: "Smileys" },
      { emoji: "👺", name: "goblin", aliases: ["goblin", "monster"], category: "Smileys" },
      { emoji: "👻", name: "ghost", aliases: ["ghost", "spooky", "halloween"], category: "Smileys" },
      { emoji: "👽", name: "alien", aliases: ["alien", "ufo", "space"], category: "Smileys" },
      { emoji: "👾", name: "space_invader", aliases: ["space_invader", "alien", "game"], category: "Smileys" },
      { emoji: "🤖", name: "robot", aliases: ["robot", "bot"], category: "Smileys" },
    ],
  },
  {
    name: "Gestures",
    icon: "👋",
    emojis: [
      { emoji: "👋", name: "wave", aliases: ["wave", "hello", "bye", "hi"], category: "Gestures" },
      { emoji: "🤚", name: "raised_back_of_hand", aliases: ["raised_back_of_hand", "stop"], category: "Gestures" },
      { emoji: "🖐️", name: "raised_hand_with_fingers_splayed", aliases: ["hand", "high_five"], category: "Gestures" },
      { emoji: "✋", name: "hand", aliases: ["hand", "stop", "high_five"], category: "Gestures" },
      { emoji: "🖖", name: "vulcan_salute", aliases: ["vulcan_salute", "spock", "star_trek"], category: "Gestures" },
      { emoji: "👌", name: "ok_hand", aliases: ["ok_hand", "ok", "perfect"], category: "Gestures" },
      { emoji: "🤌", name: "pinched_fingers", aliases: ["pinched_fingers", "italian"], category: "Gestures" },
      { emoji: "🤏", name: "pinching_hand", aliases: ["pinching_hand", "small", "tiny"], category: "Gestures" },
      { emoji: "✌️", name: "v", aliases: ["v", "peace", "victory"], category: "Gestures" },
      { emoji: "🤞", name: "crossed_fingers", aliases: ["crossed_fingers", "luck", "hope"], category: "Gestures" },
      { emoji: "🤟", name: "love_you_gesture", aliases: ["love_you_gesture", "love", "rock"], category: "Gestures" },
      { emoji: "🤘", name: "metal", aliases: ["metal", "rock", "horns"], category: "Gestures" },
      { emoji: "🤙", name: "call_me_hand", aliases: ["call_me_hand", "shaka", "hang_loose"], category: "Gestures" },
      { emoji: "👈", name: "point_left", aliases: ["point_left", "left"], category: "Gestures" },
      { emoji: "👉", name: "point_right", aliases: ["point_right", "right"], category: "Gestures" },
      { emoji: "👆", name: "point_up", aliases: ["point_up", "up"], category: "Gestures" },
      { emoji: "👇", name: "point_down", aliases: ["point_down", "down"], category: "Gestures" },
      { emoji: "☝️", name: "point_up_2", aliases: ["point_up_2", "up", "one"], category: "Gestures" },
      { emoji: "👍", name: "thumbsup", aliases: ["thumbsup", "+1", "yes", "like", "approve"], category: "Gestures" },
      { emoji: "👎", name: "thumbsdown", aliases: ["thumbsdown", "-1", "no", "dislike"], category: "Gestures" },
      { emoji: "✊", name: "fist", aliases: ["fist", "punch", "power"], category: "Gestures" },
      { emoji: "👊", name: "punch", aliases: ["punch", "fist_bump"], category: "Gestures" },
      { emoji: "🤛", name: "fist_left", aliases: ["fist_left", "fist_bump"], category: "Gestures" },
      { emoji: "🤜", name: "fist_right", aliases: ["fist_right", "fist_bump"], category: "Gestures" },
      { emoji: "👏", name: "clap", aliases: ["clap", "applause", "bravo"], category: "Gestures" },
      { emoji: "🙌", name: "raised_hands", aliases: ["raised_hands", "hooray", "celebrate"], category: "Gestures" },
      { emoji: "👐", name: "open_hands", aliases: ["open_hands", "hug"], category: "Gestures" },
      { emoji: "🤲", name: "palms_up_together", aliases: ["palms_up_together", "prayer"], category: "Gestures" },
      { emoji: "🤝", name: "handshake", aliases: ["handshake", "deal", "agreement"], category: "Gestures" },
      { emoji: "🙏", name: "pray", aliases: ["pray", "please", "thanks", "namaste"], category: "Gestures" },
      { emoji: "✍️", name: "writing_hand", aliases: ["writing_hand", "write"], category: "Gestures" },
      { emoji: "💪", name: "muscle", aliases: ["muscle", "strong", "flex", "bicep"], category: "Gestures" },
      { emoji: "🦾", name: "mechanical_arm", aliases: ["mechanical_arm", "robot", "prosthetic"], category: "Gestures" },
      { emoji: "🦵", name: "leg", aliases: ["leg", "kick"], category: "Gestures" },
      { emoji: "🦶", name: "foot", aliases: ["foot", "kick"], category: "Gestures" },
    ],
  },
  {
    name: "Hearts",
    icon: "❤️",
    emojis: [
      { emoji: "❤️", name: "heart", aliases: ["heart", "love", "red_heart"], category: "Hearts" },
      { emoji: "🧡", name: "orange_heart", aliases: ["orange_heart"], category: "Hearts" },
      { emoji: "💛", name: "yellow_heart", aliases: ["yellow_heart"], category: "Hearts" },
      { emoji: "💚", name: "green_heart", aliases: ["green_heart"], category: "Hearts" },
      { emoji: "💙", name: "blue_heart", aliases: ["blue_heart"], category: "Hearts" },
      { emoji: "💜", name: "purple_heart", aliases: ["purple_heart"], category: "Hearts" },
      { emoji: "🖤", name: "black_heart", aliases: ["black_heart"], category: "Hearts" },
      { emoji: "🤍", name: "white_heart", aliases: ["white_heart"], category: "Hearts" },
      { emoji: "🤎", name: "brown_heart", aliases: ["brown_heart"], category: "Hearts" },
      { emoji: "💔", name: "broken_heart", aliases: ["broken_heart", "heartbreak"], category: "Hearts" },
      { emoji: "❤️‍🔥", name: "heart_on_fire", aliases: ["heart_on_fire", "passion"], category: "Hearts" },
      { emoji: "❤️‍🩹", name: "mending_heart", aliases: ["mending_heart", "healing"], category: "Hearts" },
      { emoji: "💕", name: "two_hearts", aliases: ["two_hearts", "love"], category: "Hearts" },
      { emoji: "💞", name: "revolving_hearts", aliases: ["revolving_hearts", "love"], category: "Hearts" },
      { emoji: "💓", name: "heartbeat", aliases: ["heartbeat", "love"], category: "Hearts" },
      { emoji: "💗", name: "heartpulse", aliases: ["heartpulse", "love"], category: "Hearts" },
      { emoji: "💖", name: "sparkling_heart", aliases: ["sparkling_heart", "love"], category: "Hearts" },
      { emoji: "💘", name: "cupid", aliases: ["cupid", "love", "arrow"], category: "Hearts" },
      { emoji: "💝", name: "gift_heart", aliases: ["gift_heart", "love", "present"], category: "Hearts" },
      { emoji: "💟", name: "heart_decoration", aliases: ["heart_decoration"], category: "Hearts" },
      { emoji: "💋", name: "kiss", aliases: ["kiss", "lipstick", "lips"], category: "Hearts" },
    ],
  },
  {
    name: "Objects",
    icon: "💡",
    emojis: [
      { emoji: "💡", name: "bulb", aliases: ["bulb", "idea", "light"], category: "Objects" },
      { emoji: "🔥", name: "fire", aliases: ["fire", "hot", "lit", "flame"], category: "Objects" },
      { emoji: "⭐", name: "star", aliases: ["star", "favorite"], category: "Objects" },
      { emoji: "🌟", name: "star2", aliases: ["star2", "glowing_star", "sparkle"], category: "Objects" },
      { emoji: "✨", name: "sparkles", aliases: ["sparkles", "magic", "shine"], category: "Objects" },
      { emoji: "💫", name: "dizzy", aliases: ["dizzy", "star", "sparkle"], category: "Objects" },
      { emoji: "🎉", name: "tada", aliases: ["tada", "party", "celebrate", "hooray"], category: "Objects" },
      { emoji: "🎊", name: "confetti_ball", aliases: ["confetti_ball", "party", "celebrate"], category: "Objects" },
      { emoji: "🎁", name: "gift", aliases: ["gift", "present", "birthday"], category: "Objects" },
      { emoji: "🎈", name: "balloon", aliases: ["balloon", "party", "birthday"], category: "Objects" },
      { emoji: "🎂", name: "birthday", aliases: ["birthday", "cake", "party"], category: "Objects" },
      { emoji: "🍰", name: "cake", aliases: ["cake", "dessert", "slice"], category: "Objects" },
      { emoji: "🧁", name: "cupcake", aliases: ["cupcake", "dessert"], category: "Objects" },
      { emoji: "🍕", name: "pizza", aliases: ["pizza", "food"], category: "Objects" },
      { emoji: "🍔", name: "hamburger", aliases: ["hamburger", "burger", "food"], category: "Objects" },
      { emoji: "🍟", name: "fries", aliases: ["fries", "food", "french_fries"], category: "Objects" },
      { emoji: "🌮", name: "taco", aliases: ["taco", "food", "mexican"], category: "Objects" },
      { emoji: "🌯", name: "burrito", aliases: ["burrito", "food", "wrap"], category: "Objects" },
      { emoji: "🍿", name: "popcorn", aliases: ["popcorn", "movie", "snack"], category: "Objects" },
      { emoji: "☕", name: "coffee", aliases: ["coffee", "cafe", "espresso"], category: "Objects" },
      { emoji: "🍵", name: "tea", aliases: ["tea", "green_tea", "drink"], category: "Objects" },
      { emoji: "🍺", name: "beer", aliases: ["beer", "drink", "alcohol"], category: "Objects" },
      { emoji: "🍻", name: "beers", aliases: ["beers", "cheers", "drink"], category: "Objects" },
      { emoji: "🥂", name: "champagne_glass", aliases: ["champagne_glass", "cheers", "toast"], category: "Objects" },
      { emoji: "🍷", name: "wine_glass", aliases: ["wine_glass", "wine", "drink"], category: "Objects" },
      { emoji: "💻", name: "computer", aliases: ["computer", "laptop", "mac"], category: "Objects" },
      { emoji: "🖥️", name: "desktop_computer", aliases: ["desktop_computer", "pc"], category: "Objects" },
      { emoji: "📱", name: "iphone", aliases: ["iphone", "phone", "mobile"], category: "Objects" },
      { emoji: "📧", name: "email", aliases: ["email", "mail", "envelope"], category: "Objects" },
      { emoji: "📝", name: "memo", aliases: ["memo", "note", "write"], category: "Objects" },
      { emoji: "📚", name: "books", aliases: ["books", "reading", "library"], category: "Objects" },
      { emoji: "📖", name: "book", aliases: ["book", "reading", "open_book"], category: "Objects" },
      { emoji: "🔑", name: "key", aliases: ["key", "lock", "password"], category: "Objects" },
      { emoji: "🔒", name: "lock", aliases: ["lock", "security", "private"], category: "Objects" },
      { emoji: "🔓", name: "unlock", aliases: ["unlock", "open"], category: "Objects" },
      { emoji: "🛠️", name: "tools", aliases: ["tools", "hammer_and_wrench"], category: "Objects" },
      { emoji: "⚙️", name: "gear", aliases: ["gear", "settings", "cog"], category: "Objects" },
      { emoji: "🎵", name: "musical_note", aliases: ["musical_note", "music", "note"], category: "Objects" },
      { emoji: "🎶", name: "notes", aliases: ["notes", "music", "musical_notes"], category: "Objects" },
      { emoji: "🎧", name: "headphones", aliases: ["headphones", "music", "audio"], category: "Objects" },
      { emoji: "🎤", name: "microphone", aliases: ["microphone", "mic", "karaoke"], category: "Objects" },
      { emoji: "📷", name: "camera", aliases: ["camera", "photo"], category: "Objects" },
      { emoji: "🎬", name: "clapper", aliases: ["clapper", "movie", "film"], category: "Objects" },
      { emoji: "📺", name: "tv", aliases: ["tv", "television", "screen"], category: "Objects" },
      { emoji: "🎮", name: "video_game", aliases: ["video_game", "game", "controller"], category: "Objects" },
      { emoji: "🎯", name: "dart", aliases: ["dart", "target", "bullseye"], category: "Objects" },
      { emoji: "🏆", name: "trophy", aliases: ["trophy", "win", "award", "champion"], category: "Objects" },
      { emoji: "🥇", name: "first_place_medal", aliases: ["first_place_medal", "gold", "winner"], category: "Objects" },
      { emoji: "🥈", name: "second_place_medal", aliases: ["second_place_medal", "silver"], category: "Objects" },
      { emoji: "🥉", name: "third_place_medal", aliases: ["third_place_medal", "bronze"], category: "Objects" },
      { emoji: "⚽", name: "soccer", aliases: ["soccer", "football", "ball"], category: "Objects" },
      { emoji: "🏀", name: "basketball", aliases: ["basketball", "ball", "sport"], category: "Objects" },
      { emoji: "🏈", name: "football", aliases: ["football", "american_football"], category: "Objects" },
      { emoji: "⚾", name: "baseball", aliases: ["baseball", "ball", "sport"], category: "Objects" },
      { emoji: "💰", name: "moneybag", aliases: ["moneybag", "money", "dollar", "rich"], category: "Objects" },
      { emoji: "💵", name: "dollar", aliases: ["dollar", "money", "cash"], category: "Objects" },
      { emoji: "💳", name: "credit_card", aliases: ["credit_card", "payment", "card"], category: "Objects" },
      { emoji: "💎", name: "gem", aliases: ["gem", "diamond", "jewel"], category: "Objects" },
      { emoji: "⏰", name: "alarm_clock", aliases: ["alarm_clock", "time", "wake"], category: "Objects" },
      { emoji: "⏳", name: "hourglass", aliases: ["hourglass", "time", "sand"], category: "Objects" },
      { emoji: "🔔", name: "bell", aliases: ["bell", "notification", "ring"], category: "Objects" },
      { emoji: "🔕", name: "no_bell", aliases: ["no_bell", "mute", "silent"], category: "Objects" },
    ],
  },
  {
    name: "Nature",
    icon: "🌸",
    emojis: [
      { emoji: "☀️", name: "sunny", aliases: ["sunny", "sun", "weather"], category: "Nature" },
      { emoji: "🌙", name: "moon", aliases: ["moon", "night", "crescent_moon"], category: "Nature" },
      { emoji: "⭐", name: "star", aliases: ["star", "night"], category: "Nature" },
      { emoji: "🌈", name: "rainbow", aliases: ["rainbow", "pride"], category: "Nature" },
      { emoji: "☁️", name: "cloud", aliases: ["cloud", "weather"], category: "Nature" },
      { emoji: "⛈️", name: "thunder_cloud_and_rain", aliases: ["storm", "thunder", "lightning"], category: "Nature" },
      { emoji: "❄️", name: "snowflake", aliases: ["snowflake", "winter", "cold"], category: "Nature" },
      { emoji: "🌊", name: "ocean", aliases: ["ocean", "wave", "sea", "water"], category: "Nature" },
      { emoji: "🌸", name: "cherry_blossom", aliases: ["cherry_blossom", "flower", "spring"], category: "Nature" },
      { emoji: "🌺", name: "hibiscus", aliases: ["hibiscus", "flower"], category: "Nature" },
      { emoji: "🌻", name: "sunflower", aliases: ["sunflower", "flower"], category: "Nature" },
      { emoji: "🌹", name: "rose", aliases: ["rose", "flower", "love"], category: "Nature" },
      { emoji: "🌷", name: "tulip", aliases: ["tulip", "flower"], category: "Nature" },
      { emoji: "🌼", name: "blossom", aliases: ["blossom", "flower"], category: "Nature" },
      { emoji: "🍀", name: "four_leaf_clover", aliases: ["four_leaf_clover", "lucky", "clover"], category: "Nature" },
      { emoji: "🌿", name: "herb", aliases: ["herb", "plant", "green"], category: "Nature" },
      { emoji: "🍃", name: "leaves", aliases: ["leaves", "leaf", "wind"], category: "Nature" },
      { emoji: "🍂", name: "fallen_leaf", aliases: ["fallen_leaf", "autumn", "fall"], category: "Nature" },
      { emoji: "🍁", name: "maple_leaf", aliases: ["maple_leaf", "autumn", "canada"], category: "Nature" },
      { emoji: "🌴", name: "palm_tree", aliases: ["palm_tree", "tropical", "beach"], category: "Nature" },
      { emoji: "🌳", name: "deciduous_tree", aliases: ["deciduous_tree", "tree", "nature"], category: "Nature" },
      { emoji: "🌲", name: "evergreen_tree", aliases: ["evergreen_tree", "tree", "pine"], category: "Nature" },
      { emoji: "🐶", name: "dog", aliases: ["dog", "puppy", "pet"], category: "Nature" },
      { emoji: "🐱", name: "cat", aliases: ["cat", "kitten", "pet"], category: "Nature" },
      { emoji: "🐭", name: "mouse", aliases: ["mouse", "rat"], category: "Nature" },
      { emoji: "🐹", name: "hamster", aliases: ["hamster", "pet"], category: "Nature" },
      { emoji: "🐰", name: "rabbit", aliases: ["rabbit", "bunny"], category: "Nature" },
      { emoji: "🦊", name: "fox_face", aliases: ["fox_face", "fox"], category: "Nature" },
      { emoji: "🐻", name: "bear", aliases: ["bear", "teddy"], category: "Nature" },
      { emoji: "🐼", name: "panda_face", aliases: ["panda_face", "panda"], category: "Nature" },
      { emoji: "🐨", name: "koala", aliases: ["koala"], category: "Nature" },
      { emoji: "🐯", name: "tiger", aliases: ["tiger"], category: "Nature" },
      { emoji: "🦁", name: "lion", aliases: ["lion", "lion_face"], category: "Nature" },
      { emoji: "🐮", name: "cow", aliases: ["cow"], category: "Nature" },
      { emoji: "🐷", name: "pig", aliases: ["pig"], category: "Nature" },
      { emoji: "🐸", name: "frog", aliases: ["frog"], category: "Nature" },
      { emoji: "🐵", name: "monkey_face", aliases: ["monkey_face", "monkey"], category: "Nature" },
      { emoji: "🙈", name: "see_no_evil", aliases: ["see_no_evil", "monkey"], category: "Nature" },
      { emoji: "🙉", name: "hear_no_evil", aliases: ["hear_no_evil", "monkey"], category: "Nature" },
      { emoji: "🙊", name: "speak_no_evil", aliases: ["speak_no_evil", "monkey"], category: "Nature" },
      { emoji: "🐔", name: "chicken", aliases: ["chicken", "hen"], category: "Nature" },
      { emoji: "🐧", name: "penguin", aliases: ["penguin"], category: "Nature" },
      { emoji: "🐦", name: "bird", aliases: ["bird"], category: "Nature" },
      { emoji: "🦆", name: "duck", aliases: ["duck"], category: "Nature" },
      { emoji: "🦅", name: "eagle", aliases: ["eagle", "bird"], category: "Nature" },
      { emoji: "🦉", name: "owl", aliases: ["owl", "bird"], category: "Nature" },
      { emoji: "🦇", name: "bat", aliases: ["bat"], category: "Nature" },
      { emoji: "🐺", name: "wolf", aliases: ["wolf"], category: "Nature" },
      { emoji: "🐗", name: "boar", aliases: ["boar", "pig"], category: "Nature" },
      { emoji: "🐴", name: "horse", aliases: ["horse"], category: "Nature" },
      { emoji: "🦄", name: "unicorn", aliases: ["unicorn", "magical"], category: "Nature" },
      { emoji: "🐝", name: "bee", aliases: ["bee", "honeybee"], category: "Nature" },
      { emoji: "🐛", name: "bug", aliases: ["bug", "insect"], category: "Nature" },
      { emoji: "🦋", name: "butterfly", aliases: ["butterfly"], category: "Nature" },
      { emoji: "🐌", name: "snail", aliases: ["snail", "slow"], category: "Nature" },
      { emoji: "🐚", name: "shell", aliases: ["shell", "sea"], category: "Nature" },
      { emoji: "🐢", name: "turtle", aliases: ["turtle"], category: "Nature" },
      { emoji: "🐍", name: "snake", aliases: ["snake"], category: "Nature" },
      { emoji: "🦎", name: "lizard", aliases: ["lizard"], category: "Nature" },
      { emoji: "🦂", name: "scorpion", aliases: ["scorpion"], category: "Nature" },
      { emoji: "🦀", name: "crab", aliases: ["crab"], category: "Nature" },
      { emoji: "🦑", name: "squid", aliases: ["squid"], category: "Nature" },
      { emoji: "🐙", name: "octopus", aliases: ["octopus"], category: "Nature" },
      { emoji: "🦐", name: "shrimp", aliases: ["shrimp", "prawn"], category: "Nature" },
      { emoji: "🐠", name: "tropical_fish", aliases: ["tropical_fish", "fish"], category: "Nature" },
      { emoji: "🐟", name: "fish", aliases: ["fish"], category: "Nature" },
      { emoji: "🐬", name: "dolphin", aliases: ["dolphin"], category: "Nature" },
      { emoji: "🦈", name: "shark", aliases: ["shark"], category: "Nature" },
      { emoji: "🐳", name: "whale", aliases: ["whale"], category: "Nature" },
      { emoji: "🐋", name: "whale2", aliases: ["whale2"], category: "Nature" },
    ],
  },
  {
    name: "Symbols",
    icon: "✅",
    emojis: [
      { emoji: "✅", name: "white_check_mark", aliases: ["white_check_mark", "check", "done", "yes"], category: "Symbols" },
      { emoji: "❌", name: "x", aliases: ["x", "no", "cross", "wrong"], category: "Symbols" },
      { emoji: "⭕", name: "o", aliases: ["o", "circle"], category: "Symbols" },
      { emoji: "❗", name: "exclamation", aliases: ["exclamation", "bang", "important"], category: "Symbols" },
      { emoji: "❓", name: "question", aliases: ["question", "confused"], category: "Symbols" },
      { emoji: "❕", name: "grey_exclamation", aliases: ["grey_exclamation"], category: "Symbols" },
      { emoji: "❔", name: "grey_question", aliases: ["grey_question"], category: "Symbols" },
      { emoji: "💯", name: "100", aliases: ["100", "perfect", "score"], category: "Symbols" },
      { emoji: "🔴", name: "red_circle", aliases: ["red_circle", "red"], category: "Symbols" },
      { emoji: "🟠", name: "orange_circle", aliases: ["orange_circle", "orange"], category: "Symbols" },
      { emoji: "🟡", name: "yellow_circle", aliases: ["yellow_circle", "yellow"], category: "Symbols" },
      { emoji: "🟢", name: "green_circle", aliases: ["green_circle", "green"], category: "Symbols" },
      { emoji: "🔵", name: "blue_circle", aliases: ["blue_circle", "blue"], category: "Symbols" },
      { emoji: "🟣", name: "purple_circle", aliases: ["purple_circle", "purple"], category: "Symbols" },
      { emoji: "⚫", name: "black_circle", aliases: ["black_circle", "black"], category: "Symbols" },
      { emoji: "⚪", name: "white_circle", aliases: ["white_circle", "white"], category: "Symbols" },
      { emoji: "🟤", name: "brown_circle", aliases: ["brown_circle", "brown"], category: "Symbols" },
      { emoji: "🔺", name: "small_red_triangle", aliases: ["small_red_triangle", "up"], category: "Symbols" },
      { emoji: "🔻", name: "small_red_triangle_down", aliases: ["small_red_triangle_down", "down"], category: "Symbols" },
      { emoji: "➕", name: "plus", aliases: ["plus", "add"], category: "Symbols" },
      { emoji: "➖", name: "minus", aliases: ["minus", "subtract"], category: "Symbols" },
      { emoji: "➗", name: "divide", aliases: ["divide", "division"], category: "Symbols" },
      { emoji: "✖️", name: "multiply", aliases: ["multiply", "times"], category: "Symbols" },
      { emoji: "♻️", name: "recycle", aliases: ["recycle", "environment"], category: "Symbols" },
      { emoji: "♾️", name: "infinity", aliases: ["infinity", "forever"], category: "Symbols" },
      { emoji: "💲", name: "dollar_sign", aliases: ["dollar_sign", "money"], category: "Symbols" },
      { emoji: "©️", name: "copyright", aliases: ["copyright"], category: "Symbols" },
      { emoji: "®️", name: "registered", aliases: ["registered"], category: "Symbols" },
      { emoji: "™️", name: "tm", aliases: ["tm", "trademark"], category: "Symbols" },
      { emoji: "🔗", name: "link", aliases: ["link", "url", "chain"], category: "Symbols" },
      { emoji: "➡️", name: "arrow_right", aliases: ["arrow_right", "right"], category: "Symbols" },
      { emoji: "⬅️", name: "arrow_left", aliases: ["arrow_left", "left"], category: "Symbols" },
      { emoji: "⬆️", name: "arrow_up", aliases: ["arrow_up", "up"], category: "Symbols" },
      { emoji: "⬇️", name: "arrow_down", aliases: ["arrow_down", "down"], category: "Symbols" },
      { emoji: "↗️", name: "arrow_upper_right", aliases: ["arrow_upper_right"], category: "Symbols" },
      { emoji: "↘️", name: "arrow_lower_right", aliases: ["arrow_lower_right"], category: "Symbols" },
      { emoji: "↙️", name: "arrow_lower_left", aliases: ["arrow_lower_left"], category: "Symbols" },
      { emoji: "↖️", name: "arrow_upper_left", aliases: ["arrow_upper_left"], category: "Symbols" },
      { emoji: "🔃", name: "arrows_clockwise", aliases: ["arrows_clockwise", "refresh"], category: "Symbols" },
      { emoji: "🔄", name: "arrows_counterclockwise", aliases: ["arrows_counterclockwise", "sync"], category: "Symbols" },
      { emoji: "🔙", name: "back", aliases: ["back"], category: "Symbols" },
      { emoji: "🔚", name: "end", aliases: ["end"], category: "Symbols" },
      { emoji: "🔛", name: "on", aliases: ["on"], category: "Symbols" },
      { emoji: "🔜", name: "soon", aliases: ["soon"], category: "Symbols" },
      { emoji: "🔝", name: "top", aliases: ["top"], category: "Symbols" },
      { emoji: "⚠️", name: "warning", aliases: ["warning", "caution", "alert"], category: "Symbols" },
      { emoji: "🚫", name: "no_entry_sign", aliases: ["no_entry_sign", "forbidden", "prohibited"], category: "Symbols" },
      { emoji: "🚷", name: "no_pedestrians", aliases: ["no_pedestrians"], category: "Symbols" },
      { emoji: "🚯", name: "do_not_litter", aliases: ["do_not_litter"], category: "Symbols" },
      { emoji: "🚳", name: "no_bicycles", aliases: ["no_bicycles"], category: "Symbols" },
      { emoji: "🚱", name: "non_potable_water", aliases: ["non_potable_water"], category: "Symbols" },
      { emoji: "📵", name: "no_mobile_phones", aliases: ["no_mobile_phones"], category: "Symbols" },
      { emoji: "🔞", name: "underage", aliases: ["underage", "18"], category: "Symbols" },
      { emoji: "ℹ️", name: "information_source", aliases: ["information_source", "info"], category: "Symbols" },
    ],
  },
];

// Flatten all emojis for search
export const allEmojis: Emoji[] = emojiCategories.flatMap((cat) => cat.emojis);

// Search emojis by name or alias
export function searchEmojis(query: string, limit = 8): Emoji[] {
  const lowerQuery = query.toLowerCase();
  const results: Emoji[] = [];
  const seen = new Set<string>();

  // First pass: exact name match
  for (const emoji of allEmojis) {
    if (emoji.name === lowerQuery && !seen.has(emoji.emoji)) {
      results.push(emoji);
      seen.add(emoji.emoji);
    }
  }

  // Second pass: name starts with query
  for (const emoji of allEmojis) {
    if (results.length >= limit) break;
    if (emoji.name.startsWith(lowerQuery) && !seen.has(emoji.emoji)) {
      results.push(emoji);
      seen.add(emoji.emoji);
    }
  }

  // Third pass: alias starts with query
  for (const emoji of allEmojis) {
    if (results.length >= limit) break;
    if (
      emoji.aliases.some((alias) => alias.startsWith(lowerQuery)) &&
      !seen.has(emoji.emoji)
    ) {
      results.push(emoji);
      seen.add(emoji.emoji);
    }
  }

  // Fourth pass: name contains query
  for (const emoji of allEmojis) {
    if (results.length >= limit) break;
    if (emoji.name.includes(lowerQuery) && !seen.has(emoji.emoji)) {
      results.push(emoji);
      seen.add(emoji.emoji);
    }
  }

  // Fifth pass: alias contains query
  for (const emoji of allEmojis) {
    if (results.length >= limit) break;
    if (
      emoji.aliases.some((alias) => alias.includes(lowerQuery)) &&
      !seen.has(emoji.emoji)
    ) {
      results.push(emoji);
      seen.add(emoji.emoji);
    }
  }

  return results;
}
