/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTabsRouteImport } from './routes/_app/_tabs'
import { Route as AppTabsIndexRouteImport } from './routes/_app/_tabs/index'
import { Route as AppSkillsStudioRouteImport } from './routes/_app/skills.studio'
import { Route as AppSkillsHubRouteImport } from './routes/_app/skills.hub'
import { Route as AppConversationIdRouteImport } from './routes/_app/conversation.$id'
import { Route as AppClusterIdRouteImport } from './routes/_app/cluster.$id'
import { Route as AppTabsPointsRouteImport } from './routes/_app/_tabs/points'
import { Route as AppTabsLinesRouteImport } from './routes/_app/_tabs/lines'
import { Route as AppTabsCirclesRouteImport } from './routes/_app/_tabs/circles'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTabsRoute = AppTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => AppRoute,
} as any)
const AppTabsIndexRoute = AppTabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTabsRoute,
} as any)
const AppSkillsStudioRoute = AppSkillsStudioRouteImport.update({
  id: '/skills/studio',
  path: '/skills/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsHubRoute = AppSkillsHubRouteImport.update({
  id: '/skills/hub',
  path: '/skills/hub',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationIdRoute = AppConversationIdRouteImport.update({
  id: '/conversation/$id',
  path: '/conversation/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClusterIdRoute = AppClusterIdRouteImport.update({
  id: '/cluster/$id',
  path: '/cluster/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTabsPointsRoute = AppTabsPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AppTabsRoute,
} as any)
const AppTabsLinesRoute = AppTabsLinesRouteImport.update({
  id: '/lines',
  path: '/lines',
  getParentRoute: () => AppTabsRoute,
} as any)
const AppTabsCirclesRoute = AppTabsCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppTabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppTabsIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/circles': typeof AppTabsCirclesRoute
  '/lines': typeof AppTabsLinesRoute
  '/points': typeof AppTabsPointsRoute
  '/cluster/$id': typeof AppClusterIdRoute
  '/conversation/$id': typeof AppConversationIdRoute
  '/skills/hub': typeof AppSkillsHubRoute
  '/skills/studio': typeof AppSkillsStudioRoute
}
export interface FileRoutesByTo {
  '/': typeof AppTabsIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/circles': typeof AppTabsCirclesRoute
  '/lines': typeof AppTabsLinesRoute
  '/points': typeof AppTabsPointsRoute
  '/cluster/$id': typeof AppClusterIdRoute
  '/conversation/$id': typeof AppConversationIdRoute
  '/skills/hub': typeof AppSkillsHubRoute
  '/skills/studio': typeof AppSkillsStudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/_tabs': typeof AppTabsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/_tabs/circles': typeof AppTabsCirclesRoute
  '/_app/_tabs/lines': typeof AppTabsLinesRoute
  '/_app/_tabs/points': typeof AppTabsPointsRoute
  '/_app/cluster/$id': typeof AppClusterIdRoute
  '/_app/conversation/$id': typeof AppConversationIdRoute
  '/_app/skills/hub': typeof AppSkillsHubRoute
  '/_app/skills/studio': typeof AppSkillsStudioRoute
  '/_app/_tabs/': typeof AppTabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/circles'
    | '/lines'
    | '/points'
    | '/cluster/$id'
    | '/conversation/$id'
    | '/skills/hub'
    | '/skills/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/circles'
    | '/lines'
    | '/points'
    | '/cluster/$id'
    | '/conversation/$id'
    | '/skills/hub'
    | '/skills/studio'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/_tabs'
    | '/_app/settings'
    | '/_app/_tabs/circles'
    | '/_app/_tabs/lines'
    | '/_app/_tabs/points'
    | '/_app/cluster/$id'
    | '/_app/conversation/$id'
    | '/_app/skills/hub'
    | '/_app/skills/studio'
    | '/_app/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_tabs': {
      id: '/_app/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppTabsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_tabs/': {
      id: '/_app/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppTabsIndexRouteImport
      parentRoute: typeof AppTabsRoute
    }
    '/_app/skills/studio': {
      id: '/_app/skills/studio'
      path: '/skills/studio'
      fullPath: '/skills/studio'
      preLoaderRoute: typeof AppSkillsStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills/hub': {
      id: '/_app/skills/hub'
      path: '/skills/hub'
      fullPath: '/skills/hub'
      preLoaderRoute: typeof AppSkillsHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversation/$id': {
      id: '/_app/conversation/$id'
      path: '/conversation/$id'
      fullPath: '/conversation/$id'
      preLoaderRoute: typeof AppConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cluster/$id': {
      id: '/_app/cluster/$id'
      path: '/cluster/$id'
      fullPath: '/cluster/$id'
      preLoaderRoute: typeof AppClusterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_tabs/points': {
      id: '/_app/_tabs/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof AppTabsPointsRouteImport
      parentRoute: typeof AppTabsRoute
    }
    '/_app/_tabs/lines': {
      id: '/_app/_tabs/lines'
      path: '/lines'
      fullPath: '/lines'
      preLoaderRoute: typeof AppTabsLinesRouteImport
      parentRoute: typeof AppTabsRoute
    }
    '/_app/_tabs/circles': {
      id: '/_app/_tabs/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AppTabsCirclesRouteImport
      parentRoute: typeof AppTabsRoute
    }
  }
}

interface AppTabsRouteChildren {
  AppTabsCirclesRoute: typeof AppTabsCirclesRoute
  AppTabsLinesRoute: typeof AppTabsLinesRoute
  AppTabsPointsRoute: typeof AppTabsPointsRoute
  AppTabsIndexRoute: typeof AppTabsIndexRoute
}

const AppTabsRouteChildren: AppTabsRouteChildren = {
  AppTabsCirclesRoute: AppTabsCirclesRoute,
  AppTabsLinesRoute: AppTabsLinesRoute,
  AppTabsPointsRoute: AppTabsPointsRoute,
  AppTabsIndexRoute: AppTabsIndexRoute,
}

const AppTabsRouteWithChildren =
  AppTabsRoute._addFileChildren(AppTabsRouteChildren)

interface AppRouteChildren {
  AppTabsRoute: typeof AppTabsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppClusterIdRoute: typeof AppClusterIdRoute
  AppConversationIdRoute: typeof AppConversationIdRoute
  AppSkillsHubRoute: typeof AppSkillsHubRoute
  AppSkillsStudioRoute: typeof AppSkillsStudioRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTabsRoute: AppTabsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppClusterIdRoute: AppClusterIdRoute,
  AppConversationIdRoute: AppConversationIdRoute,
  AppSkillsHubRoute: AppSkillsHubRoute,
  AppSkillsStudioRoute: AppSkillsStudioRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
