/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppComposeRouteImport } from './routes/_app/compose'
import { Route as AppTabsRouteImport } from './routes/_app/_tabs'
import { Route as AppTabsIndexRouteImport } from './routes/_app/_tabs/index'
import { Route as AppConversationIdRouteImport } from './routes/_app/conversation.$id'
import { Route as AppTabsRequestsRouteImport } from './routes/_app/_tabs/requests'
import { Route as AppTabsPointsRouteImport } from './routes/_app/_tabs/points'
import { Route as AppTabsCirclesRouteImport } from './routes/_app/_tabs/circles'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppComposeRoute = AppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppRoute,
} as any)
const AppTabsRoute = AppTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => AppRoute,
} as any)
const AppTabsIndexRoute = AppTabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTabsRoute,
} as any)
const AppConversationIdRoute = AppConversationIdRouteImport.update({
  id: '/conversation/$id',
  path: '/conversation/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTabsRequestsRoute = AppTabsRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppTabsRoute,
} as any)
const AppTabsPointsRoute = AppTabsPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AppTabsRoute,
} as any)
const AppTabsCirclesRoute = AppTabsCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppTabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppTabsIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/compose': typeof AppComposeRoute
  '/settings': typeof AppSettingsRoute
  '/circles': typeof AppTabsCirclesRoute
  '/points': typeof AppTabsPointsRoute
  '/requests': typeof AppTabsRequestsRoute
  '/conversation/$id': typeof AppConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppTabsIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/compose': typeof AppComposeRoute
  '/settings': typeof AppSettingsRoute
  '/circles': typeof AppTabsCirclesRoute
  '/points': typeof AppTabsPointsRoute
  '/requests': typeof AppTabsRequestsRoute
  '/conversation/$id': typeof AppConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/_tabs': typeof AppTabsRouteWithChildren
  '/_app/compose': typeof AppComposeRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/_tabs/circles': typeof AppTabsCirclesRoute
  '/_app/_tabs/points': typeof AppTabsPointsRoute
  '/_app/_tabs/requests': typeof AppTabsRequestsRoute
  '/_app/conversation/$id': typeof AppConversationIdRoute
  '/_app/_tabs/': typeof AppTabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/compose'
    | '/settings'
    | '/circles'
    | '/points'
    | '/requests'
    | '/conversation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/compose'
    | '/settings'
    | '/circles'
    | '/points'
    | '/requests'
    | '/conversation/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/_tabs'
    | '/_app/compose'
    | '/_app/settings'
    | '/_app/_tabs/circles'
    | '/_app/_tabs/points'
    | '/_app/_tabs/requests'
    | '/_app/conversation/$id'
    | '/_app/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compose': {
      id: '/_app/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AppComposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_tabs': {
      id: '/_app/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppTabsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_tabs/': {
      id: '/_app/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppTabsIndexRouteImport
      parentRoute: typeof AppTabsRoute
    }
    '/_app/conversation/$id': {
      id: '/_app/conversation/$id'
      path: '/conversation/$id'
      fullPath: '/conversation/$id'
      preLoaderRoute: typeof AppConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_tabs/requests': {
      id: '/_app/_tabs/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppTabsRequestsRouteImport
      parentRoute: typeof AppTabsRoute
    }
    '/_app/_tabs/points': {
      id: '/_app/_tabs/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof AppTabsPointsRouteImport
      parentRoute: typeof AppTabsRoute
    }
    '/_app/_tabs/circles': {
      id: '/_app/_tabs/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AppTabsCirclesRouteImport
      parentRoute: typeof AppTabsRoute
    }
  }
}

interface AppTabsRouteChildren {
  AppTabsCirclesRoute: typeof AppTabsCirclesRoute
  AppTabsPointsRoute: typeof AppTabsPointsRoute
  AppTabsRequestsRoute: typeof AppTabsRequestsRoute
  AppTabsIndexRoute: typeof AppTabsIndexRoute
}

const AppTabsRouteChildren: AppTabsRouteChildren = {
  AppTabsCirclesRoute: AppTabsCirclesRoute,
  AppTabsPointsRoute: AppTabsPointsRoute,
  AppTabsRequestsRoute: AppTabsRequestsRoute,
  AppTabsIndexRoute: AppTabsIndexRoute,
}

const AppTabsRouteWithChildren =
  AppTabsRoute._addFileChildren(AppTabsRouteChildren)

interface AppRouteChildren {
  AppTabsRoute: typeof AppTabsRouteWithChildren
  AppComposeRoute: typeof AppComposeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppConversationIdRoute: typeof AppConversationIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTabsRoute: AppTabsRouteWithChildren,
  AppComposeRoute: AppComposeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppConversationIdRoute: AppConversationIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
